-- 0002: reference data generated from project-docs/doc-module-map.md (section 4).
-- Registry rows = the screen-actions table + module-to-module calls from the use cases.
-- Error codes = the closed list, with the human text shown on screen.
insert into registry_entries ("caller","moduleName","actionName","allowedRole") values
  ('S01','home','get_coach_home','coach'),
  ('S02','trainees','list_trainees','coach'),
  ('S02','trainees','invite_trainee','coach'),
  ('S03','trainees','get_trainee_card','coach'),
  ('S04','programs','get_active_program','coach'),
  ('S04','programs','save_program','coach'),
  ('S04','programs','swap_exercise','coach'),
  ('S04','programs','start_new_program','coach'),
  ('S04','exercises','list_exercises','coach'),
  ('S05','exercises','list_exercises','coach'),
  ('S05','exercises','create_exercise','coach'),
  ('S05','exercises','attach_video','coach'),
  ('S05','exercises','get_exercise','coach'),
  ('S06','results','list_results','coach'),
  ('S06','feedback','add_coach_note','coach'),
  ('S06','feedback','get_workout_notes','coach'),
  ('S07','coins','set_personal_goal','coach'),
  ('S08','payments','create_payment_request','coach'),
  ('S08','payments','list_payments','coach'),
  ('S08','invoices','list_invoices','coach'),
  ('S09','challenges','create_challenge','coach'),
  ('S09','challenges','get_current_challenge','coach'),
  ('S09','challenges','list_completions','coach'),
  ('S09','challenges','mark_prize_delivered','coach'),
  ('S10','coins','manage_rewards','coach'),
  ('S10','coins','mark_reward_delivered','coach'),
  ('S11','classes','publish_class','coach'),
  ('S11','classes','cancel_class','coach'),
  ('S11','classes','list_upcoming_classes','coach'),
  ('S11','classes','list_registrations','coach'),
  ('S11','classes','mark_attendance','coach'),
  ('S11','classes','decide_late_cancel','coach'),
  ('S12','settings','get_settings','coach'),
  ('S12','settings','update_settings','coach'),
  ('S13','home','get_trainee_home','trainee'),
  ('S13','classes','respond_to_spot_offer','trainee'),
  ('S13','notifications','list_notifications','trainee'),
  ('S13','notifications','mark_read','trainee'),
  ('S14','programs','get_active_program','trainee'),
  ('S14','results','log_workout','trainee'),
  ('S14','exercises','get_exercise','trainee'),
  ('S16','results','list_results','trainee'),
  ('S16','results','correct_result','trainee'),
  ('S16','feedback','get_workout_notes','trainee'),
  ('S17','classes','list_upcoming_classes','trainee'),
  ('S17','classes','register','trainee'),
  ('S17','classes','cancel_registration','trainee'),
  ('S17','classes','request_late_cancel','trainee'),
  ('S18','coins','get_balance','trainee'),
  ('S18','coins','redeem_reward','trainee'),
  ('S19','payments','list_payments','trainee'),
  ('S19','payments','pay_demo','trainee'),
  ('S19','invoices','list_invoices','trainee'),
  ('S20','challenges','get_current_challenge','trainee'),
  ('S21','progress','get_progress_chart','coach'),
  ('S21','progress','get_progress_chart','trainee'),
  ('S22','trainees','accept_invite','trainee'),
  ('M04','feedback','build_feedback','module'),
  ('M04','coins','award','module'),
  ('M04','challenges','check_progress','module'),
  ('M04','programs','get_active_program','module'),
  ('M06','progress','detect_personal_records','module'),
  ('M06','notifications','notify_in_app','module'),
  ('M08','coins','award','module'),
  ('M08','results','list_results','module'),
  ('M08','programs','get_active_program','module'),
  ('M11','coins','award','module'),
  ('M11','notifications','notify_in_app','module'),
  ('M09','payment_gateway','charge','module'),
  ('M09','invoices','create_invoice','module'),
  ('M05','results','list_results','module'),
  ('M07','results','list_results','module'),
  ('M13','payments','list_payments','module'),
  ('M13','classes','list_upcoming_classes','module'),
  ('M13','challenges','get_current_challenge','module'),
  ('M13','trainees','list_trainees','module'),
  ('M13','coins','get_balance','module'),
  ('M13','programs','get_active_program','module'),
  ('M13','feedback','get_workout_notes','module'),
  ('M13','results','list_results','module'),
  ('M13','notifications','list_notifications','module'),
  ('M01','settings','get_settings','module'),
  ('M02','settings','get_settings','module'),
  ('M06','settings','get_settings','module'),
  ('M07','settings','get_settings','module'),
  ('M09','settings','get_settings','module'),
  ('M11','settings','get_settings','module'),
  ('M13','settings','get_settings','module'),
  ('M08','settings','get_settings','module');

insert into error_codes ("errorCode","developerText","humanText") values
  ('CALLER_MISSING','אין שדה פונה','משהו השתבש. נסה שוב'),
  ('CALLER_INVALID','הפונה אינו ברשימה הסגורה','משהו השתבש. נסה שוב'),
  ('ACTION_NOT_ALLOWED','אין שורה ב-Registry','הפעולה הזו אינה זמינה כאן'),
  ('AUDIT_FAILED','הרישום ביומן נכשל, והבקשה לא נותבה','הפעולה לא בוצעה. נסה שוב בעוד רגע'),
  ('NOT_ALLOWED','הפונה אינו מורשה על הנתון הזה','אין לך גישה לזה'),
  ('STORAGE_UNAVAILABLE','המסד לא החזיר תשובה','השינוי לא נשמר כרגע. נסה שוב'),
  ('VALUE_NOT_SET','ערך נדרש חסר ב-SETTINGS ("עדיין לא")','הערך עוד לא הוגדר בהגדרות'),
  ('PROGRAM_INVALID','יעד חסר או לא חיובי','חסר מידע בתרגיל. השלם סטים, חזרות ומשקל'),
  ('NO_ACTIVE_PROGRAM','אין תוכנית פעילה','התוכנית שלך בהכנה אצל המאמן'),
  ('RESULT_INVALID','תוצאה שלילית או לא מספרית','יש ערך לא תקין באחד הסטים'),
  ('NOTE_INVALID','הערה ריקה או ארוכה מדי','ההערה ריקה או ארוכה מדי'),
  ('INVITE_INVALID','פרט קשר לא תקין','פרט הקשר לא תקין'),
  ('INVITE_EXPIRED','ההזמנה פגה','ההזמנה כבר לא בתוקף. בקש חדשה'),
  ('INVITE_DELIVERY_FAILED','הערוץ לא אישר שליחה','ההזמנה לא נשלחה. אפשר לשלוח שוב או להעתיק קישור'),
  ('VIDEO_INVALID','לא סרטון, או קישור לא תקין','זה לא נראה כמו סרטון'),
  ('VIDEO_TOO_LONG','אורך מעל המותר','אפשר להעלות סרטון של עד דקה'),
  ('UPLOAD_FAILED','אחסון הקבצים לא אישר','הסרטון לא עלה. נסה שוב'),
  ('PAYMENT_ALREADY_PAID','בקשה ששולמה','הבקשה הזו כבר שולמה'),
  ('PAYMENT_GATEWAY_UNAVAILABLE','השער לא הגיב','התשלום לא הושלם. לא בוצע חיוב'),
  ('COINS_INSUFFICIENT','יתרה נמוכה מהמחיר','אין מספיק מטבעות'),
  ('COINS_ALREADY_AWARDED','האירוע כבר זוכה','לא מוצג למשתמש'),
  ('CHALLENGE_EXISTS','כבר יש אתגר לשבוע','כבר יש אתגר השבוע'),
  ('CHALLENGE_INVALID','יעד חסר או לא חיובי','חסר יעד לאתגר'),
  ('CLASS_INVALID','פרטי שיעור חסרים','חסרים פרטים בשיעור'),
  ('ALREADY_REGISTERED','כבר רשום או ממתין','אתה כבר רשום לשיעור הזה'),
  ('CANCEL_TOO_LATE','בתוך חלון הביטול','אפשר לבטל עד 24 שעות לפני. אפשר לבקש חריגה'),
  ('SPOT_OFFER_EXPIRED','זמן ההיענות להצעה עבר','המקום כבר הוצע לבא בתור');
